"""
Strategy: BTC Momentum 1H
Generated by Atlas analytics discovery pipeline.
Optimized parameters: rsi_period=18, overbought=80.72, oversold=17.56
"""
import numpy as np
import pandas as pd


def calculate_rsi(data: np.ndarray, period: int = 14) -> np.ndarray:
    """Calculate RSI indicator."""
    delta = np.diff(data, prepend=data[0])
    gain = np.where(delta > 0, delta, 0)
    loss = np.where(delta < 0, -delta, 0)
    
    # Exponential moving average
    alpha = 1.0 / period
    avg_gain = np.zeros_like(data)
    avg_loss = np.zeros_like(data)
    
    avg_gain[period] = np.mean(gain[1:period+1])
    avg_loss[period] = np.mean(loss[1:period+1])
    
    for i in range(period + 1, len(data)):
        avg_gain[i] = (1 - alpha) * avg_gain[i-1] + alpha * gain[i]
        avg_loss[i] = (1 - alpha) * avg_loss[i-1] + alpha * loss[i]
    
    rs = np.where(avg_loss != 0, avg_gain / avg_loss, 0)
    rsi = 100 - (100 / (1 + rs))
    rsi[:period] = np.nan
    
    return rsi


def generate_signals(df: pd.DataFrame) -> np.ndarray:
    """
    Generate trading signals from OHLCV data.
    
    Args:
        df: DataFrame with columns: open, high, low, close, volume
        
    Returns:
        Array of signals: -1 (short), 0 (neutral), +1 (long)
    """
    close = df['close'].values
    n = len(close)
    signals = np.zeros(n)
    
    # Calculate RSI
    rsi = calculate_rsi(close, 18)
    
    position = 0
    for i in range(1, n):
        if np.isnan(rsi[i]):
            continue
        
        # Entry on oversold/overbought crossings
        if rsi[i-1] < 17.56 and rsi[i] >= 17.56 and position <= 0:
            signals[i] = 1  # Long
            position = 1
        elif rsi[i-1] > 80.72 and rsi[i] <= 80.72 and position >= 0:
            signals[i] = -1  # Short
            position = -1
        # Exit near neutral
        elif position == 1 and rsi[i] > 50:
            signals[i] = 0
            position = 0
        elif position == -1 and rsi[i] < 50:
            signals[i] = 0
            position = 0
    
    return signals


STRATEGY_META = {
    "name": "BTC Momentum 1H",
    "asset": "BTC",
    "timeframe": "1H",
    "strategy_type": "RSI Momentum",
    "parameters": {
        "rsi_period": 18,
        "overbought": 80.72,
        "oversold": 17.56
    }
}
