"""
Strategy: ETH Trend Crossover 15M
Generated by Atlas analytics discovery pipeline.
Optimized parameters: fast_period=9, slow_period=21, signal_period=5
"""
import numpy as np
import pandas as pd


def _ema(values: np.ndarray, period: int) -> np.ndarray:
    """Compute exponential moving average."""
    result = np.full_like(values, np.nan, dtype=float)
    if len(values) < period:
        return result
    alpha = 2.0 / (period + 1)
    result[period - 1] = np.mean(values[:period])
    for i in range(period, len(values)):
        result[i] = alpha * values[i] + (1 - alpha) * result[i - 1]
    return result


def generate_signals(df: pd.DataFrame) -> np.ndarray:
    """
    Generate trading signals from OHLCV data.

    Args:
        df: DataFrame with columns: open, high, low, close, volume

    Returns:
        Array of signals: -1 (short), 0 (neutral), +1 (long)
    """
    close = df["close"].values
    n = len(close)
    signals = np.zeros(n)

    fast = _ema(close, 9)
    slow = _ema(close, 21)
    # Smoothed signal line on the spread to reduce chop
    spread = fast - slow
    signal_line = _ema(np.nan_to_num(spread), 5)

    position = 0
    for i in range(21, n):
        if np.isnan(fast[i]) or np.isnan(slow[i]):
            continue

        prev_spread = spread[i - 1]
        curr_spread = spread[i]

        if prev_spread < 0 and curr_spread >= 0 and position <= 0:
            # Fast crosses above slow — go long
            signals[i] = 1
            position = 1
        elif prev_spread > 0 and curr_spread <= 0 and position >= 0:
            # Fast crosses below slow — go short
            signals[i] = -1
            position = -1
        else:
            signals[i] = position  # Hold existing position

    return signals


STRATEGY_META = {
    "name": "ETH Trend Crossover 15M",
    "asset": "ETH",
    "timeframe": "15M",
    "strategy_type": "Trend Following",
    "parameters": {
        "fast_period": 9,
        "slow_period": 21,
        "signal_period": 5,
    },
}
