"""
Strategy: SOL Trend 1D
Generated by Atlas analytics discovery pipeline.
Optimized parameters: fast_period=13, slow_period=30
"""
import numpy as np
import pandas as pd


def generate_signals(df: pd.DataFrame) -> np.ndarray:
    """
    Generate trading signals from OHLCV data.
    
    Args:
        df: DataFrame with columns: open, high, low, close, volume
        
    Returns:
        Array of signals: -1 (short), 0 (neutral), +1 (long)
    """
    close = df['close'].values
    n = len(close)
    signals = np.zeros(n)
    
    # Calculate moving averages
    fast_ma = pd.Series(close).rolling(window=13).mean().values
    slow_ma = pd.Series(close).rolling(window=30).mean().values
    
    # Generate signals on crossover
    for i in range(1, n):
        if np.isnan(fast_ma[i]) or np.isnan(slow_ma[i]):
            continue
        if fast_ma[i-1] <= slow_ma[i-1] and fast_ma[i] > slow_ma[i]:
            signals[i] = 1  # Long
        elif fast_ma[i-1] >= slow_ma[i-1] and fast_ma[i] < slow_ma[i]:
            signals[i] = -1  # Short
    
    return signals


STRATEGY_META = {
    "name": "SOL Trend 1D",
    "asset": "SOL",
    "timeframe": "1D",
    "strategy_type": "MA Crossover",
    "parameters": {
        "fast_period": 13,
        "slow_period": 30
    }
}
