from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    direction: int
    confidence: float
    size_pct: float
    reason: str
    timestamp: datetime = field(default_factory=datetime.utcnow)
    current_price: float = 0.0
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    strategy_slug: str = ""
    asset: str = ""
    timeframe: str = ""

    @property
    def is_actionable(self) -> bool:
        return self.direction != 0 and self.size_pct > 0

    @property
    def direction_str(self) -> str:
        return {-1: "SHORT", 0: "NEUTRAL", 1: "LONG"}[self.direction]


@dataclass
class Position:
    """Open position on GMX V2."""

    market_id: str
    asset: str
    size: float
    entry_price: float
    current_price: float
    unrealized_pnl: float
    leverage: float
    liquidation_price: Optional[float] = None

    @property
    def direction(self) -> str:
        return "long" if self.size > 0 else "short"

    @property
    def pnl_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        base_return = (self.current_price - self.entry_price) / self.entry_price
        if self.size < 0:
            base_return = -base_return
        if self.leverage and self.leverage > 0:
            return base_return * self.leverage
        return base_return


@dataclass
class VaultSnapshot:
    """Snapshot of vault state."""

    vault_address: str
    timestamp: datetime
    tvl: float
    share_price: float
    depositor_count: int
    positions: List[Position]
    total_unrealized_pnl: float

    def to_dict(self) -> dict:
        return {
            "vault_address": self.vault_address,
            "timestamp": self.timestamp.isoformat(),
            "tvl": self.tvl,
            "share_price": self.share_price,
            "depositor_count": self.depositor_count,
            "positions": [vars(p) for p in self.positions],
            "total_unrealized_pnl": self.total_unrealized_pnl,
        }
